### ISSUE TITLE
Dandelion Voting - Update app details

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/dandelion-voting-app#20]
- General description

- Update the features that have been changed.

- Add new features added

**Comment by lkngtn** [comment]
# Dandelion Voting
## Description
Create and participate in votes

## Details
Similar to the original voting app, the Dandelion voting app is used to create and participate in votes. However, the Dandelion voting app has additional functionality to enable an Organization to restrict voters from performing action using the Aragon permissions system if the user has contributed to a vote passing, until that vote has been enacted. 

## Features
* See details about open and past votes, including how many tokens have voted and how much time is left before a vote is over.
* Give the Voting app permission to perform actions in other apps so those actions have to be approved by a tokenholder vote before they can be executed.
* Add a delay period after a vote is approved but before it can be executed. 
* Allow organizations to configure the permissions to perform actions based on whether or not the user has voted yes in a pending vote.
