### ISSUE TITLE
Filters not working as expected

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/dandelion-voting-app#26]
When selecting `closed` it shows `upcoming` votes.
Also, when selecting `upcoming` it shows `closed` and `upcoming` votes

<img width="722" alt="Screen Shot 2019-11-02 at 12 17 56 AM" src="https://user-images.githubusercontent.com/22663232/68065754-5b9d9680-fd0c-11e9-9c94-c40145e200fa.png">

**Comment by rperez89** [comment]
fixed with commit 
65d10fd on #14
